:guid: %guid%
:user: %user%
:ssh_command: %ssh_password%
:markup-in-source: verbatim,attributes,quotes
:my_deep_var_underbars: %my_deep_var%
:my_deep_var_dots: %my.deep.var%
:openshift_console_url: %openshift_console_url%
:openshift_api_url: %openshift_api_url%

As organizations modernize their applications and adopt a containerization strategy,  breaking down traditional monolithic applications into a set of unique microservices is the logical next step. With the decoupling of the traditional applications into a set of microservices, the importance of data exchange between the services is paramount. In this workshop you will learn how to deploy applications on OpenShift, deploy CockroachDB using Red Hat OpenShift Database Access and create an event driven architecture for reliable data exchange between microservices using OpenShift, CockroachDB and Kafka to create an outbox pattern.

== What will you learn

* Using a Java Spring Boot microservice application, learn how to implement a transactional outbox pattern using CockroachDB’s Change Data Capture feature.
* OpenShift AMQ Stream for implementing an Apache Kafka messaging platform.
* OpenShift Database Access for self-service access to CockroachDB Cloud.
* OpenShift S2I (Source-to-image) for building container images from source code.


== Reference

* Fruit Shop application based on Java Spring Boot
* Kafka Consumer application based on Python 3


=== Lab Access

You can access your lab environment as {user} with password "{ssh_password}" with the following command:

[source,bash,options="nowrap",subs="{markup-in-source}"]
----
%ssh_command%
----

Your lab GUID is "{guid}".
Your console url is "{openshift_console_url}"

An example var was set to %example_var%.
